import { ProjectCardData } from "@/components/ui/project-card";

export const projectData: ProjectCardData[] = [
    {
		id: "7",
		title: "SWEJobTracker",
		subtitle: "Job tracking site for SWEs",
		excerpt: [
			"SWEJobTracker watches the boards recruiters actually use, and curates the most relevant job postings for you.",
			"It helps you track your applications, and provides a simple interface to manage your job search.",
		],
		createdAt: "July 19, 2026",
		url: "https://swejob-tracker.vercel.app",
		urlLabel: "View Project",
		techStack: [
			"React",
			"Next.js",
			"TypeScript",
			"Tailwind CSS",
            "Claude",
			"PostgreSQL",
            "Prisma",
            "BetterAuth",
		],
		thumbnail: "/projects-images/swejobtracker.png",
		thumbnailAlt: "Screenshot of the SWEJobTracker site",
	},
	{
		id: "6",
		title: "mi·me·mo",
		subtitle: "a minimal memo app",
		excerpt: [
			"A minimal memo making application based on a privacy focused approach of storing/sharing notes.",
			"Your notes stay with you, in your browser address bar. No accounts or sign-ups.",
			"Share these notes with the world without worrying about privacy or censorship.",
		],
		createdAt: "October 24, 2025",
		url: "https://mi-me-mo.vercel.app",
		urlLabel: "View Project",
		techStack: [
			"React",
			"Next.js",
			"TypeScript",
			"Tailwind CSS",
			"PostgreSQL",
			"Drizzle ORM",
		],
		thumbnail: "/projects-images/mimemo.png",
		thumbnailAlt: "Screenshot of the mi·me·mo memo editor",
	},
	{
		id: "5",
		title: "My Portfolio",
		subtitle: "Yup! This very one!",
		excerpt: [
			"A portfolio showcasing my creative and technical skills through innovative design and interactive experiences.",
			"DM me to get my detailed CV.",
		],
		createdAt: "August 27, 2025",
		url: "https://github.com/mehulsinha73/mehulsinha73.github.io",
		urlLabel: "View Github",
		techStack: [
			"React",
			"Next.js",
			"TypeScript",
			"Tailwind CSS",
			"Framer Motion",
		],
		thumbnail: "/projects-images/portfolio.png",
		thumbnailAlt: "Screenshot of Mehul Sinha's portfolio home page",
	},
	{
		id: "4",
		title: "Circles",
		subtitle: "Social media app for communities",
		excerpt: [
			"A social media app designed to foster community engagement and interaction through the concept of friend/community circles.",
		],
		createdAt: "September 10, 2025",
		url: "https://github.com/mehulsinha73/circle-ui",
		urlLabel: "View Github",
		techStack: ["React Native", "Expo", "TypeScript", "Django"],
		thumbnail: "/projects-images/circle.png",
		thumbnailAlt: "Screenshot of the Circles social media app",
	},
	{
		id: "3",
		title: "Abodewave",
		subtitle: "AI Saas to manage rental properties",
		excerpt: [
			"A SaaS platform that leverages AI to streamline rental property management, offering features like automated tenant procurement and screening, rent collection, and maintenance scheduling.",
		],
		createdAt: "June 18, 2025",
		url: "https://github.com/mehulsinha73/abodewave-frontend",
		urlLabel: "View Github",
		techStack: [
			"React",
			"Next.js",
			"TypeScript",
			"Python",
			"Django",
			"PostgreSQL",
			"BetterAuth",
		],
		thumbnail: "/projects-images/abodewave.png",
		thumbnailAlt: "Screenshot of the Abodewave logo",
	},
	{
		id: "2",
		title: "Andpods",
		subtitle: "Android app for Airpods settings",
		excerpt: [
			"Developed a simple android app to bring Apple-only Airpods settings to android.",
		],
		createdAt: "November 23, 2024",
		url: "https://github.com/mehulsinha73/Andpods",
		urlLabel: "View Github",
		techStack: ["Kotlin", "Android SDK"],
		thumbnail: "/projects-images/airpods.jpg",
		thumbnailAlt: "Andpods Image - represented by a pair of Airpods",
	},
	{
		id: "1",
		title: "DescAI",
		subtitle: "Chatbot to query group of websites",
		excerpt: [
			"Developed a LLM RAG-based Chatbot that scraped, processed, and generated an AI model based on data retrieved from a collection of websites.",
			"Used it on websites with convoluted and hidden layouts to obtain data based on my requirements.",
		],
		createdAt: "August 09, 2024",
		url: "https://github.com/mehulsinha73/DescAI",
		urlLabel: "View Github",
		techStack: ["Python", "LangChain", "ChromaDB", "Ollama", "OpenAI"],
		thumbnail: "/projects-images/blank.png",
		thumbnailAlt: "DescAI, a RAG chatbot for querying groups of websites",
	},
];
