'use client';
import { cn } from "@/lib/utils";
import type { ComponentProps } from "react";

export function Code(props: ComponentProps<"code"> & { "data-theme"?: string }) {
    // Don't style <pre><code></pre> components (generated by rehype pretty code)
    const classes = cn("font-mono tracking-normal text-sm", props.className );

    return <code {...props} className={classes} />;
}